Update the pull-waveform script
pnsn/Mt_Baker_LF_Research pull request #3
Opened 2024-10-09 21:30 UTC by Benz-Poobua

- Add pull-waveform script, fetching data from dataframe, evid, IRIS client
- Add demo notebook

2024-10-09 21:35 UTC, nts345045 requested changes
Update demo.ipynb per comment

2024-10-09 21:35 UTC, nts345045 commented on src/notebooks/demo.ipynb
Rename to describe what it is a demo of and add a small markdown block at the top of the notebook describing what the notebook does and which *.py script it is using for methods

2024-10-10 04:32 UTC, Benz-Poobua commented
- Add the pull_wf_by_evid.py and comments
- Add the tutorial file using pull_wf_by_evid module and necessary comments

2024-10-10 15:25 UTC, nts345045 approved these changes
Revisions complete

2024-10-10 15:25 UTC, merged