Add curating-event script and its tutorial
pnsn/Mt_Baker_LF_Research pull request #4
Opened 2024-10-11 01:33 UTC by Benz-Poobua

### python script
1. Rename the fields, Boolean correction, Time correction
2. Curate well-located events based on: 
                1. 6+ observations (P or S wave picks): nobs >= 6
                2. 4+ observing stations: nsta >= 4
                3. no fixed values (depth, epicenter, or time): ['fdepth', 'fepi', 'ftime'] are set to False
                4. a minimum observing station distance of no more than 10 km: distance <= 10
                5. horizontal and vertical errors of 10 km or less: erhor & sdep <= 10
                6. travel time RMS misfit of no more than 1 second: wrms <= 1
### notebook
- provide the tutorial on how to call the module and generate the output file (.csv) in `src/data/MtBaker_50km_radius_origins_curated`

2024-10-11 17:08 UTC, nts345045 requested changes

2024-10-11 17:08 UTC, nts345045 commented on .DS_Store
Please eliminate .DS_Store files (and similar auto-generated files/directories) from your repository.

2024-10-11 17:08 UTC, nts345045 commented on src/.DS_Store
Please eliminate .DS_Store files (and similar auto-generated files/directories) from your repository.

2024-10-11 17:08 UTC, nts345045 commented on src/notebooks/MtBaker_well_located.ipynb
Please add some visualization of the subset origins. Particular parameters of interest are event type, location, origin time, magnitude, and parameters used to create the data subset. In addition, please provide figures comparing the distribution of each filtering parameter for the whole data set and the data subset.

2024-10-11 17:08 UTC, nts345045 commented on src/notebooks/MtBaker_well_located.ipynb
Finally, add a markdown block at the end of the notebook and write a set of observations for informative patterns you see in the data (note that not all data combinations may be particularly informative).

2024-10-11 17:08 UTC, nts345045 commented on src/python/well_located_events.py
Add a doctoring to the `convert_to_unix` method.

2024-10-14 05:48 UTC, Benz-Poobua commented
- Add docstring to the `convert_to_unix` method.
- Add subplots to display the well-located and whole datasets

2024-10-14 19:40 UTC, nts345045 requested changes
Code updates look good - conduct the intermediate data cleanup tasks for a merge approval.

2024-10-14 19:40 UTC, nts345045 commented on data/Processed Datasets/MtBaker_50km_radius_origins_cleaned.csv
For cleanliness of the main repository, do not include intermediate output files as part of the repository.

2024-10-14 19:40 UTC, nts345045 commented on data/Processed Datasets/MtBaker_50km_radius_origins_curated.csv
For cleanliness of the main repository, do not include intermediate output files as part of the repository.

2024-10-14 19:40 UTC, nts345045 commented on data/Processed Datasets/MtBaker_50km_radius_origins_cleaned.csv
You can do the following:
add a `processed_data` directory to the root directory of your local repository
save intermediate data files in `processed_data`
add `processed_data` to your `.gitignore`

2024-10-14 19:40 UTC, nts345045 commented on data/Processed Datasets/MtBaker_50km_radius_origins_curated.csv
You can do the following:
add a `processed_data` directory to the root directory of your local repository
save intermediate data files in `processed_data`
add `processed_data` to your `.gitignore`

2024-10-16 22:35 UTC, nts345045 approved these changes

2024-10-16 22:35 UTC, merged