Add well-located evid
pnsn/Mt_Baker_LF_Research pull request #5
Opened 2024-10-16 23:28 UTC by Benz-Poobua

- Add well-located evids in CSV format

2024-10-23 14:34 UTC, nts345045 requested changes
Update code and resubmit

2024-10-23 14:34 UTC, nts345045 commented on results/tables/well_located_mtBaker_evids.csv
Contains duplicates (I also made this error) - for completeness, please add in an element to your code that removes duplicate EVIDs.

2024-10-23 14:34 UTC, nts345045 commented on results/tables/well_located_mtBaker_evids.csv
This can be accomplished using the `drop_duplicates` method for pandas DataFrames and Series.

2024-10-23 14:34 UTC, nts345045 commented on results/tables/well_located_mtBaker_evids.csv
Additionally, I realized that the initial data (events within 50 km) should be subset to 20km from Mt. Baker to prevent including another swarm that occurred away from the volcano, but in the region. Add this filter using the `mbs_distance_km` field.

2024-10-23 20:02 UTC, Benz-Poobua commented
Resubmited the evid CSV file with updated well_located_events.py

2024-10-29 05:23 UTC, Benz-Poobua commented
I fixed path-related bugs in `wf_query_from_eventbank.py`.

2024-10-29 16:23 UTC, nts345045 approved these changes

2024-10-29 16:23 UTC, merged